# netlify.toml configuration for React routing

[build]
  publish = "build"
  command = "npm run build"  # Adjust if you use yarn

# Redirect all React Router paths to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Redirects for specific routes to handle them properly via React Router
[[redirects]]
  from = "/admin/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/dashboard/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/profile/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/wallet/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/trade/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/testimonials/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/login/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/signup/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/forgot-password/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/reset-password/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/admin/verify/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/roles/verify/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/admin/forgot-password/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/admin/signup/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/admin/login/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/role/login/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/role/no-access/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/overview/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/notifications/*"
  to = "/index.html"
  status = 200
  force = true
